---
version: '3.9'

services:
  frontend:
    image: ghcr.io/fosten/plone-happy-site-frontend:${STACK_PARAM:-latest}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://happybaseball-com_backend:8080/Plone
      RAZZLE_API_PATH: https://happybaseball.com
    depends_on:
      - backend
    networks:
      - traefik-public
      - traefik-happy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Service
        - traefik.http.services.happy-frontend.loadbalancer.server.port=3000
        # Routers
        ## /
        - traefik.http.routers.happy-frontend.rule=Host(`happybaseball.com`)
        - traefik.http.routers.happy-frontend.entrypoints=websecure
        - traefik.http.routers.happy-frontend.tls=true
        - traefik.http.routers.happy-frontend.tls.certresolver=mydnschallenge
        - traefik.http.routers.happy-frontend.service=happy-frontend
        - traefik.http.routers.happy-frontend.middlewares=gzip

  backend:
    image: ghcr.io/fosten/plone-happy-site-backend:${STACK_PARAM:-latest}
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-plone}' user='${DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-plone}' port='${DB_PORT:-5432}'"
    networks:
      - traefik-public
      - traefik-happy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Services
        - traefik.http.services.happy-backend.loadbalancer.server.port=8080
        # Middlewares
        ## VHM rewrite /++api++/
        - "traefik.http.middlewares.happy-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.happy-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/https/happybaseball.com/Plone/++api++/VirtualHostRoot$$1"
        ## VHM rewrite /ClassicUI/
        - "traefik.http.middlewares.happy-backend-vhm-classic.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.happy-backend-vhm-classic.replacepathregex.replacement=/VirtualHostBase/https/happybaseball.com/Plone/VirtualHostRoot/_vh_ClassicUI$$1"
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.happy-backend-auth.basicauth.users=admin:${TRAEFIK_HASHED_PASSWORD}

        # Routes
        ## /++api++
        - traefik.http.routers.happy-backend-api.rule=Host(`happybaseball.com`) && PathPrefix(`/++api++`)
        - traefik.http.routers.happy-backend-api.entrypoints=websecure
        - traefik.http.routers.happy-backend-api.tls=true
        - traefik.http.routers.happy-backend-api.service=happy-backend
        - traefik.http.routers.happy-backend-api.middlewares=gzip,happy-backend-vhm-api
        ## /ClassicUI
        - traefik.http.routers.happy-backend-classic.rule=Host(`happybaseball.com`) && PathPrefix(`/ClassicUI`)
        - traefik.http.routers.happy-backend-classic.entrypoints=websecure
        - traefik.http.routers.happy-backend-classic.tls=true
        - traefik.http.routers.happy-backend-classic.service=happy-backend
        - traefik.http.routers.happy-backend-classic.middlewares=gzip,happy-backend-auth,happy-backend-vhm-classic

networks:
  traefik-public:
    external: true
  traefik-happy:
    internal: true
    driver: overlay
