---
version: '3.9'

services:
  frontend:
    image: ghcr.io/fosten/plone-happy-site-frontend:${STACK_PARAM:-latest}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://testing-happybaseball-com_backend:8080/Plone
      RAZZLE_API_PATH: https://testing.happybaseball.com
    depends_on:
      - backend
    networks:
     - traefik-public
      - traefik-testing_happy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Service
        - traefik.http.services.testing_happy-frontend.loadbalancer.server.port=3000
        # Middlewares
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.testing_happy-frontend-auth.basicauth.users=testing:${TRAEFIK_HASHED_PASSWORD}

        # Routers
        ## /
        - traefik.http.routers.testing_happy-frontend.rule=Host(`testing.happybaseball.com`)
        - traefik.http.routers.testing_happy-frontend.entrypoints=websecure
        - traefik.http.routers.testing_happy-frontend.tls=true
        - traefik.http.routers.testing_happy-frontend.tls.certresolver=mydnschallenge
        - traefik.http.routers.testing_happy-frontend.service=testing_happy-frontend
        - traefik.http.routers.testing_happy-frontend.middlewares=gzip,testing_happy-frontend-auth

  backend:
    image: ghcr.io/fosten/plone-happy-site-backend:${STACK_PARAM:-latest}
    environment:
      RELSTORAGE_DSN: "dbname='${TESTING_DB_NAME:-plone}' user='${TESTING_DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-plone}' port='${DB_PORT:-5432}'"
    networks:
      - traefik-public
      - traefik-testing_happy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == happyapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Services
        - traefik.http.services.testing_happy-backend.loadbalancer.server.port=8080
        # Middlewares
        ## VHM rewrite /++api++/
        - "traefik.http.middlewares.testing_happy-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.testing_happy-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/https/testing.happybaseball.com/Plone/++api++/VirtualHostRoot$$1"
        ## VHM rewrite /ClassicUI/
        - "traefik.http.middlewares.testing_happy-backend-vhm-classic.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.testing_happy-backend-vhm-classic.replacepathregex.replacement=/VirtualHostBase/https/testing.happybaseball.com/Plone/VirtualHostRoot/_vh_ClassicUI$$1"
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.testing_happy-backend-auth.basicauth.users=admin:${TRAEFIK_HASHED_PASSWORD}

        # Routes
        ## /++api++
        - traefik.http.routers.testing_happy-backend-api.rule=Host(`testing.happybaseball.com`) && PathPrefix(`/++api++`)
        - traefik.http.routers.testing_happy-backend-api.entrypoints=websecure
        - traefik.http.routers.testing_happy-backend-api.tls=true
        - traefik.http.routers.testing_happy-backend-api.service=testing_happy-backend
        - traefik.http.routers.testing_happy-backend-api.middlewares=gzip,testing_happy-backend-vhm-api
        ## /ClassicUI
        - traefik.http.routers.testing_happy-backend-classic.rule=Host(`testing.happybaseball.com`) && PathPrefix(`/ClassicUI`)
        - traefik.http.routers.testing_happy-backend-classic.entrypoints=websecure
        - traefik.http.routers.testing_happy-backend-classic.tls=true
        - traefik.http.routers.testing_happy-backend-classic.service=testing_happy-backend
        - traefik.http.routers.testing_happy-backend-classic.middlewares=gzip,testing_happy-backend-auth,testing_happy-backend-vhm-classic

networks:
  traefik-public:
    external: true
  traefik-testing_happy:
    internal: true
    driver: overlay
